
  - version: 5.30.0
    majorVersion: '5.30'
    prerelease: false
    date: '2019-05-28T12:33:59'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.30.0
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/92233bc5293c2eb17f3019f329cc67fd96d92bcf/5.030.000-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.30.0-slim
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/92233bc5293c2eb17f3019f329cc67fd96d92bcf/5.030.000-slim/Dockerfile

  - version: 5.28.2
    majorVersion: '5.28'
    prerelease: false
    date: '2019-05-28T12:33:59'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.28.2
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/92233bc5293c2eb17f3019f329cc67fd96d92bcf/5.028.002-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.28.2-slim
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/92233bc5293c2eb17f3019f329cc67fd96d92bcf/5.028.002-slim/Dockerfile

  - version: 5.28.1
    majorVersion: '5.28'
    prerelease: false
    date: '2019-01-28T14:26:15'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.28.1
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/65ea3a9754a5b99ffbc84fde515cfa289cffee45/5.028.001-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.28.1-slim-threaded
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/65ea3a9754a5b99ffbc84fde515cfa289cffee45/5.028.001-slim,threaded/Dockerfile

  - version: 5.28.0
    majorVersion: '5.28'
    prerelease: false
    date: '2019-01-28T14:26:15'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.28.0
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/892e2b4fbb58c48ee802cd13b34017300c630f18/5.028.000-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.28.0-slim
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/65ea3a9754a5b99ffbc84fde515cfa289cffee45/5.028.001-slim/Dockerfile

  - version: 5.26.3
    majorVersion: '5.26'
    prerelease: false
    date: '2019-05-28T12:33:59'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.26.3
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/92233bc5293c2eb17f3019f329cc67fd96d92bcf/5.026.003-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.26.3-slim
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/92233bc5293c2eb17f3019f329cc67fd96d92bcf/5.026.003-slim/Dockerfile

  - version: 5.26.2
    majorVersion: '5.26'
    prerelease: false
    date: '2018-08-12T15:54:55'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.26.2
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/892e2b4fbb58c48ee802cd13b34017300c630f18/5.026.002-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.26.2-slim
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/892e2b4fbb58c48ee802cd13b34017300c630f18/5.026.002-slim/Dockerfile

  - version: 5.26.1
    majorVersion: '5.26'
    prerelease: false
    date: '2017-12-04T12:08:42'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.26.1
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/a5c2d6c896807e9c1beec4ebac01c7f30c075bf0/5.026.001-64bit/Dockerfile

  - version: 5.26.0
    majorVersion: '5.26'
    prerelease: false
    date: '2017-08-27T01:54:33'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.26.0
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/8044d4ba7627712b6fbed84e544d2d78ca805f96/5.026.000-64bit/Dockerfile

  - version: 5.24.4
    majorVersion: '5.24'
    prerelease: false
    date: '2019-04-27T13:48:34'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.24.4
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/9c264844428eaef70ec0c8eefc213cae53fdf12f/5.024.004-main/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: perl:5.24.4-slim
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/9c264844428eaef70ec0c8eefc213cae53fdf12f/5.024.004-slim/Dockerfile

  - version: 5.24.3
    majorVersion: '5.24'
    prerelease: false
    date: '2017-12-04T12:08:42'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.24.3
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/a5c2d6c896807e9c1beec4ebac01c7f30c075bf0/5.024.003-64bit/Dockerfile

  - version: 5.24.2
    majorVersion: '5.24'
    prerelease: false
    date: '2017-08-27T01:54:33'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.24.2
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/8044d4ba7627712b6fbed84e544d2d78ca805f96/5.024.002-64bit/Dockerfile

  - version: 5.24.1
    majorVersion: '5.24'
    prerelease: false
    date: '2017-03-04T09:36:48'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps
        imageRepository: perl:5.24.1
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/8b57a74dbc745fb2723bc60ba98768846dae37f6/5.024.001-64bit/Dockerfile

  - version: 5.22.4
    majorVersion: '5.22'
    prerelease: false
    date: '2018-04-19T23:31:37'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: perl:5.22.4
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/1c201e950ebe90f35c449f69df6ca7151cb0068d/5.022.004-64bit/Dockerfile

  - version: 5.22.3
    majorVersion: '5.22'
    prerelease: false
    date: '2017-03-04T09:36:48'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps
        imageRepository: perl:5.22.3
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/8b57a74dbc745fb2723bc60ba98768846dae37f6/5.022.003-64bit/Dockerfile

  - version: 5.20.0
    majorVersion: '5.20'
    prerelease: false
    date: '2014-07-08T00:26:17'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps
        imageRepository: perl:5.20.0
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/34796bd21f9f48816e0dbb2e5126593d83588f78/5.020.000-64bit/Dockerfile

  - version: '5.20'
    majorVersion: '5.20'
    prerelease: false
    date: '2014-07-08T00:26:17'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps
        imageRepository: perl:5.20
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/34796bd21f9f48816e0dbb2e5126593d83588f78/5.020.000-64bit/Dockerfile

  - version: 5.18.2
    majorVersion: '5.18'
    prerelease: false
    date: '2014-07-08T00:26:17'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps
        imageRepository: perl:5.18.2
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/34796bd21f9f48816e0dbb2e5126593d83588f78/5.018.002-64bit/Dockerfile

  - version: '5.18'
    majorVersion: '5.18'
    prerelease: false
    date: '2014-07-08T00:26:17'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps
        imageRepository: perl:5.18
        urlRepository: https://github.com/perl/docker-perl
        urlDockerfile: https://raw.githubusercontent.com/perl/docker-perl/34796bd21f9f48816e0dbb2e5126593d83588f78/5.018.002-64bit/Dockerfile
