
  - version: '3.6'
    majorVersion: '3.6'
    prerelease: false
    date: '2019-05-06T16:07:30'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 5
        image: buildpack-deps:jessie
        imageRepository: pypy:3.6-jessie
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/6ec92626b247be066a0c89d86521a00571cc5d44/3.6/Dockerfile

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 1
        image: debian:jessie-slim
        imageRepository: pypy:3.6-slim-jessie
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/6ec92626b247be066a0c89d86521a00571cc5d44/3.6/slim/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: pypy:3.6-stretch
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/eb8f5a1379cb955c32678e5b4824f1263af8ab09/3.6/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: pypy:3.6-slim-stretch
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/eb8f5a1379cb955c32678e5b4824f1263af8ab09/3.6/slim/Dockerfile

  - version: '3.5'
    majorVersion: '3.5'
    prerelease: false
    date: '2019-05-06T16:07:30'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 5
        image: buildpack-deps:jessie
        imageRepository: pypy:3.5-jessie
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/a25dfed4a6f684edfa44947fdb9f198962c5885a/3.5/Dockerfile

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 1
        image: debian:jessie-slim
        imageRepository: pypy:3.5-slim-jessie
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/a25dfed4a6f684edfa44947fdb9f198962c5885a/3.5/slim/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 5
        image: buildpack-deps:stretch
        imageRepository: pypy:3.5-stretch
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/2e5bca39321ccaecbfe9f387e20b43d04c270154/3.5/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 1
        image: debian:stretch-slim
        imageRepository: pypy:3.5-slim-stretch
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/2e5bca39321ccaecbfe9f387e20b43d04c270154/3.5/slim/Dockerfile

  - version: '2.7'
    majorVersion: '2.7'
    prerelease: false
    date: '2019-05-06T16:07:30'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 5
        image: buildpack-deps:jessie
        imageRepository: pypy:2.7-jessie
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/eb8f5a1379cb955c32678e5b4824f1263af8ab09/2.7/Dockerfile

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 1
        image: debian:jessie-slim
        imageRepository: pypy:2.7-slim-jessie
        urlRepository: https://github.com/docker-library/pypy
        urlDockerfile: https://raw.githubusercontent.com/docker-library/pypy/eb8f5a1379cb955c32678e5b4824f1263af8ab09/2.7/slim/Dockerfile
