
  - version: 5.0.1
    majorVersion: '5.0'
    prerelease: false
    date: '2019-04-24T13:37:42'
    current: true
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:5.0.1-xenial
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/0aafffef619fb3b1824c968cbbe2fba4ba41bd26/5.0/ubuntu/16.04/Dockerfile

      - name: Ubuntu
        releaseName: 18.04 (bionic)
        release: 18.04
        weight: 2
        image: ubuntu:18.04
        imageRepository: swift:5.0.1-bionic
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/0aafffef619fb3b1824c968cbbe2fba4ba41bd26/5.0/ubuntu/18.04/Dockerfile

  - version: 4.2.4
    majorVersion: '4.2'
    prerelease: false
    date: '2019-04-24T13:37:42'
    current: true
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.2.4
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/f0a61df2dd9a14dd6988e6017ae58cc63df37f41/4.2/ubuntu/16.04/Dockerfile

  - version: 4.2.3
    majorVersion: '4.2'
    prerelease: false
    date: '2019-04-23T13:41:28'
    current: false
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.2.3
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/75dde01ef86e98437b1206c6a58d0428dfb345a4/4.2/ubuntu/16.04/Dockerfile

  - version: 4.2.2
    majorVersion: '4.2'
    prerelease: false
    date: '2019-04-23T13:41:28'
    current: false
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.2.2
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/c5dd5e013de66da930cf1b9804797dbae11e8f9c/4.2/ubuntu/16.04/Dockerfile

  - version: 4.2.1
    majorVersion: '4.2'
    prerelease: false
    date: '2019-04-23T13:41:28'
    current: false
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.2.1
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/34aa283f9b3473ab22b2282f71773781b121af19/4.2/Dockerfile

  - version: 4.1.3
    majorVersion: '4.1'
    prerelease: false
    date: '2019-04-24T13:37:42'
    current: true
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.1.3
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/34aa283f9b3473ab22b2282f71773781b121af19/4.1/Dockerfile

  - version: 4.0.3
    majorVersion: '4.0'
    prerelease: false
    date: '2019-04-24T13:37:42'
    current: true
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.0.3
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/34aa283f9b3473ab22b2282f71773781b121af19/4.0/Dockerfile

  - version: 4.0.2
    majorVersion: '4.0'
    prerelease: false
    date: '2017-11-10T17:30:30'
    current: false
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:4.0.2
        urlRepository: https://github.com/swiftdocker/docker-swift
        urlDockerfile: https://raw.githubusercontent.com/swiftdocker/docker-swift/5c83628d4696bca62aec3136a4ee9b854e8d548e/4.0/Dockerfile

  - version: 3.1.1
    majorVersion: '3.1'
    prerelease: false
    date: '2019-04-24T13:37:42'
    current: true
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:3.1.1
        urlRepository: https://github.com/apple/swift-docker
        urlDockerfile: https://raw.githubusercontent.com/apple/swift-docker/34aa283f9b3473ab22b2282f71773781b121af19/3.1/Dockerfile

  - version: 3.1.0
    majorVersion: '3.1'
    prerelease: false
    date: '2017-10-03T16:52:47'
    current: false
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:3.1.0
        urlRepository: https://github.com/swiftdocker/docker-swift
        urlDockerfile: https://raw.githubusercontent.com/swiftdocker/docker-swift/ef9aa534705fc8ab4258c539f6304072ebae9613/Dockerfile

  - version: 3.0.2
    majorVersion: '3.0'
    prerelease: false
    date: '2017-10-03T16:52:47'
    current: false
    distributionReleases: Ubuntu
    distributions:

      - name: Ubuntu
        releaseName: 16.04 (xenial)
        release: 16.04
        weight: 2
        image: ubuntu:16.04
        imageRepository: swift:3.0.2
        urlRepository: https://github.com/swiftdocker/docker-swift
        urlDockerfile: https://raw.githubusercontent.com/swiftdocker/docker-swift/94a43272fe6411c12045414cfc797d3c0bcf2823/Dockerfile
