# goreleaser.yml
# Build customization
project_name: dlm
build:
  main: ./main.go
  binary: dlm
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - 386
  ignore:
    - goos: darwin
      goarch: 386

# Archive customization
archive:
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  format: tar.gz
  replacements:
    darwin: macOS
  format_overrides:
    - goos: windows
      format: zip

# Release customazation
release:
  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: true


# Build docker
dockers:
- image: janilton/dlm
  tag_templates:
  - '{{ .Major }}.{{ .Minor }}'
  - 'latest'
# End Build docker
