[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.2.0"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"

[[constraint]]
  name = "gopkg.in/yaml.v3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/gookit/color.v1"
  version = "1.1.7"

[prune]
  go-tests = true
  unused-packages = true