- name: DEBIAN
  before:
  after:
    - RUN apt-get update && apt-get install -y --no-install-recommends bash \
       && rm -rf /var/lib/apt/lists/*

- name: ALPINE
  before:
  after:
    - RUN apk update && apk add -y bash
