{{- range .From.Before -}}
{{ . }}
{{- end -}}

{{ .From.Description }}
{{ .From.Data }}

{{- range .From.After -}}
{{ . }}
{{ end -}}

{{ range .Before }}
{{ . }}
{{ end -}}

{{ range .Languages -}}
{{ .Description }}

{{ range .Before -}}
{{ . }}
{{ end -}}

{{ .Data }}

{{ range .After -}}
{{ . }}
{{ end -}}
{{ end -}}

{{- range .After -}}
{{ . }}
{{ end -}}
