
  - version: 1.1.1
    majorVersion: '1.1'
    prerelease: false
    date: '2019-05-17T05:59:09'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.1.1-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/36c40cb93c8ca5c717ab7395a775f5683f176e97/1.1/stretch/Dockerfile

  - version: 1.1.0
    majorVersion: '1.1'
    prerelease: false
    date: '2019-05-07T17:59:13'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.1.0-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/6e478029a0ccb80d4c86f516fdea3f80cb15dce9/1.1/stretch/Dockerfile

  - version: 1.0.4
    majorVersion: '1.0'
    prerelease: false
    date: '2019-05-17T05:59:09'
    current: true
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.0.4-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/092cb514a9994ee61ae883f53d56ea03c89a3c0c/1.0/stretch/Dockerfile

  - version: 1.0.3
    majorVersion: '1.0'
    prerelease: false
    date: '2019-05-07T17:59:13'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.0.3-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/60c9e91e86668dfd86f19034ebee211dfe3dd423/1.0/stretch/Dockerfile

  - version: 1.0.2
    majorVersion: '1.0'
    prerelease: false
    date: '2018-11-14T16:29:14'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.0.2-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/467c652ab40064be58ba83ed4448f139592c7525/1.0/stretch/Dockerfile

  - version: 1.0.1
    majorVersion: '1.0'
    prerelease: false
    date: '2018-10-01T16:44:11'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.0.1-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/bc6c8bde792335ec4b97ae58bbad10e965ecfaed/1.0/stretch/Dockerfile

  - version: 1.0.0
    majorVersion: '1.0'
    prerelease: false
    date: '2018-08-27T14:46:38'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:1.0.0-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/9e8bb3426385de28cfac6576baef9bf580fe0e33/1.0/stretch/Dockerfile

  - version: 0.7.0
    majorVersion: '0.7'
    prerelease: false
    date: '2018-12-19T16:51:48'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.7.0-jessie
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/467c652ab40064be58ba83ed4448f139592c7525/0/jessie/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:0.7.0-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/467c652ab40064be58ba83ed4448f139592c7525/0/stretch/Dockerfile

  - version: 0.6.4
    majorVersion: '0.6'
    prerelease: false
    date: '2018-08-06T12:18:52'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.6.4-jessie
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/4b1b740df34a21fc0edb10770d5991cb3c92d9e8/0/jessie/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:0.6.4-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/4b1b740df34a21fc0edb10770d5991cb3c92d9e8/0/stretch/Dockerfile

  - version: 0.6.3
    majorVersion: '0.6'
    prerelease: false
    date: '2018-07-20T11:17:28'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.6.3-jessie
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/3854279e1ffb49d9e34080d476ffdb7c00035455/jessie/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:0.6.3-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/3854279e1ffb49d9e34080d476ffdb7c00035455/stretch/Dockerfile

  - version: 0.6.2
    majorVersion: '0.6'
    prerelease: false
    date: '2018-05-14T12:46:12'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.6.2-jessie
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/3cb2698ed2475db46cc17d5d1cd309626ef87c1c/jessie/Dockerfile

      - name: Debian
        releaseName: 9 (stretch)
        release: 9.0
        weight: 2
        image: debian:stretch
        imageRepository: julia:0.6.2-stretch
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/3cb2698ed2475db46cc17d5d1cd309626ef87c1c/stretch/Dockerfile

  - version: 0.6.1
    majorVersion: '0.6'
    prerelease: false
    date: '2017-11-02T15:54:46'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.6.1
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/06148bd09222645c2996f50094d76aeeb9ed4556/Dockerfile

  - version: 0.6.0
    majorVersion: '0.6'
    prerelease: false
    date: '2017-08-24T16:31:51'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.6.0
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/4eff23fd0270ed08c727f1ddb10c497559732c22/Dockerfile

  - version: 0.5.2
    majorVersion: '0.5'
    prerelease: false
    date: '2017-05-30T09:19:32'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.5.2
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/0b6b28b5b0957cc491d406b798ece911a6fa5b26/Dockerfile

  - version: 0.5.1
    majorVersion: '0.5'
    prerelease: false
    date: '2017-03-06T14:42:20'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.5.1
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/8de8734c2f3547332bc1e8688ba0eff58b3a1a50/Dockerfile

  - version: 0.5.0
    majorVersion: '0.5'
    prerelease: false
    date: '2016-09-27T16:49:23'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.5.0
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/0f29b23863e4ff1c99b13a30e845b66c7468f79b/Dockerfile

  - version: 0.4.6
    majorVersion: '0.4'
    prerelease: false
    date: '2016-06-23T14:01:38'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.4.6
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/59a01cf8cdb0b0f9cc229aca415755a64226e4ed/Dockerfile

  - version: 0.4.5
    majorVersion: '0.4'
    prerelease: false
    date: '2016-06-09T12:08:41'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.4.5
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/2bb511d3378dec17ebbf417d5865ede353ba8e57/Dockerfile

  - version: 0.4.3
    majorVersion: '0.4'
    prerelease: false
    date: '2016-02-29T16:39:10'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.4.3
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/4c64514dc0f1aa0aed906af3a9a135d684c7d49e/Dockerfile

  - version: 0.4.2
    majorVersion: '0.4'
    prerelease: false
    date: '2015-12-08T13:02:08'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.4.2
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/a408dd5869f54f0adfc6b6950200f6781284d15e/Dockerfile

  - version: 0.4.1
    majorVersion: '0.4'
    prerelease: false
    date: '2015-11-09T13:56:43'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.4.1
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/52b372536c3dd5d01a7aacdd90a7246c5bf85a3d/Dockerfile

  - version: 0.4.0
    majorVersion: '0.4'
    prerelease: false
    date: '2015-10-14T14:24:25'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.4.0
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/c40ce9f16118c60bac5ce1db3e06c56d5b983d4a/Dockerfile

  - version: 0.3.11
    majorVersion: '0.3'
    prerelease: false
    date: '2015-07-28T10:04:48'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3.11
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/951fefea3d24b6d60f5e64447a1ee94f0b809448/Dockerfile

  - version: 0.3.10
    majorVersion: '0.3'
    prerelease: false
    date: '2015-06-26T16:04:56'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3.10
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/46509c3b9178016189872738ef7fb38946df970c/Dockerfile

  - version: 0.3.9
    majorVersion: '0.3'
    prerelease: false
    date: '2015-06-02T14:53:03'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3.9
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/d7222c1c8af09b75565ea89fd00658d712823120/Dockerfile

  - version: 0.3.8
    majorVersion: '0.3'
    prerelease: false
    date: '2015-05-22T16:50:08'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3.8
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/22d68e94ea5e4febf3fc6b2167e9a538e3cad4c1/Dockerfile

  - version: 0.3.7
    majorVersion: '0.3'
    prerelease: false
    date: '2015-04-01T15:16:22'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3.7
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/a85d92cbc1396ed7ba6007108412bea518271676/Dockerfile

  - version: 0.3.6
    majorVersion: '0.3'
    prerelease: false
    date: '2015-03-09T16:01:35'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3.6
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/3ebca9477c82374d1123574261b369387772de1b/Dockerfile

  - version: '0.3'
    majorVersion: '0.3'
    prerelease: false
    date: '2015-07-28T10:04:48'
    current: false
    distributionReleases: Debian
    distributions:

      - name: Debian
        releaseName: 8 (jessie)
        release: 8.0
        weight: 2
        image: debian:jessie
        imageRepository: julia:0.3
        urlRepository: https://github.com/docker-library/julia
        urlDockerfile: https://raw.githubusercontent.com/docker-library/julia/951fefea3d24b6d60f5e64447a1ee94f0b809448/Dockerfile
