- language: erlang
  alias: Erlang
  url: https://github.com/erlang/otp/releases
  sort:
    - debian:8
    - alpine:8

- language: golang
  alias: Golang
  url: https://golang.org/doc/devel/release.html

- language: haskell
  alias: Haskell
  url: https://www.haskell.org/ghc/

- language: julia
  alias: Julia
  url: https://github.com/JuliaLang/julia/releases

- language: node
  alias: Node
  url: https://nodejs.org/en/download/releases/
  sort:
    - alpine:10

- language: php
  alias: PHP
  url: https://www.php.net/releases/index.php
  sort:
    - debian:9
    - alpine:9

- language: perl
  alias: Perl
  url: http://www.cpan.org/src/

- language: python
  alias: Python
  url: https://www.python.org/downloads/
  sort:
    - debian:8

- language: ruby
  alias: Ruby
  url: https://www.ruby-lang.org/en/downloads/releases/

- language: Rust
  alias: rust
  url: https://github.com/rust-lang/rust/releases

- language: Swift
  alias: swift
  url: https://github.com/apple/swift/releases

- language: Pypy
  alias: Pypy
  url: http://doc.pypy.org/en/latest/index-of-release-notes.html

# language: jruby
# alias: Jjuby
# url: https://github.com/jruby/jruby/releases

# - language: r-base
#   alias: R
#   url: https://www.r-project.org/





